import { readdir, readFile, writeFile, unlink, access } from "node:fs/promises";
import { join } from "node:path";

interface TraefikConfig {
  appSlug: string;
  appName: string;
  externalDomain: string;
  internalUrl: string;
  publicPaths: string[];
  alephVerifyUrl: string;
}

export class TraefikManager {
  private configDir: string;

  constructor(configDir?: string) {
    this.configDir = configDir || process.env["TRAEFIK_CONFIG_DIR"] || "/data/coolify/proxy/dynamic";
  }

  getConfigPath(appSlug: string): string {
    return join(this.configDir, `aleph-app-${appSlug}.yaml`);
  }

  getForwardAuthPath(): string {
    return join(this.configDir, "aleph-forward-auth.yaml");
  }

  async ensureForwardAuth(alephVerifyUrl: string): Promise<void> {
    const path = this.getForwardAuthPath();
    const yaml = this.generateForwardAuthYaml(alephVerifyUrl);
    await writeFile(path, yaml, "utf-8");
  }

  generateForwardAuthYaml(alephVerifyUrl: string): string {
    return `# Auto-generated by Aleph Platform — DO NOT EDIT MANUALLY
# Generated: ${new Date().toISOString()}

http:
  middlewares:
    aleph-forward-auth:
      forwardAuth:
        address: "${alephVerifyUrl}"
        trustForwardHeader: true
        authResponseHeaders:
          - "X-Aleph-User-Id"
          - "X-Aleph-User-Name"
          - "X-Aleph-User-Email"
          - "X-Aleph-Org-Id"
          - "X-Aleph-Org-Name"
          - "X-Aleph-Dept"
          - "X-Aleph-Dept-Id"
          - "X-Aleph-Role"
          - "X-Aleph-Access-Level"
          - "X-Aleph-Permissions"
`;
  }

  generateYaml(config: TraefikConfig): string {
    const { appSlug, appName, externalDomain, internalUrl, publicPaths } = config;
    const slug = appSlug.replace(/[^a-z0-9-]/g, "-");

    let yaml = `# Auto-generated by Aleph Platform — DO NOT EDIT MANUALLY
# App: ${appName}
# Domain: ${externalDomain}
# Generated: ${new Date().toISOString()}

http:
  routers:
`;

    // Public paths router (higher priority)
    if (publicPaths.length > 0) {
      const pathsRule = publicPaths
        .map((p) => `PathPrefix(\`${p}\`)`)
        .join(" || ");
      yaml += `    aleph-${slug}-public:
      rule: "Host(\`${externalDomain}\`) && (${pathsRule})"
      entryPoints:
        - https
      service: aleph-${slug}-service
      priority: 200
      tls:
        certResolver: letsencrypt

`;
    }

    // Protected router (uses forward auth)
    yaml += `    aleph-${slug}-protected:
      rule: "Host(\`${externalDomain}\`)"
      entryPoints:
        - https
      service: aleph-${slug}-service
      middlewares:
        - aleph-forward-auth@file
      priority: 100
      tls:
        certResolver: letsencrypt

    aleph-${slug}-http:
      rule: "Host(\`${externalDomain}\`)"
      entryPoints:
        - http
      middlewares:
        - redirect-to-https@file
      service: aleph-${slug}-service

  services:
    aleph-${slug}-service:
      loadBalancer:
        servers:
          - url: "${internalUrl}"
`;

    return yaml;
  }

  async generateConfig(config: TraefikConfig): Promise<string> {
    // Ensure forward auth middleware exists
    await this.ensureForwardAuth(config.alephVerifyUrl);

    const yaml = this.generateYaml(config);
    const filePath = this.getConfigPath(config.appSlug);
    await writeFile(filePath, yaml, "utf-8");
    return yaml;
  }

  async removeConfig(appSlug: string): Promise<void> {
    const filePath = this.getConfigPath(appSlug);
    try {
      await unlink(filePath);
    } catch (err: unknown) {
      if (err instanceof Error && "code" in err && (err as NodeJS.ErrnoException).code !== "ENOENT") {
        throw err;
      }
    }
  }

  async configExists(appSlug: string): Promise<boolean> {
    try {
      await access(this.getConfigPath(appSlug));
      return true;
    } catch {
      return false;
    }
  }

  async readConfig(appSlug: string): Promise<string | null> {
    try {
      return await readFile(this.getConfigPath(appSlug), "utf-8");
    } catch {
      return null;
    }
  }

  async listConfigs(): Promise<string[]> {
    try {
      const files = await readdir(this.configDir);
      return files.filter((f) => f.startsWith("aleph-app-") && f.endsWith(".yaml"));
    } catch {
      return [];
    }
  }

  static resolveAlephVerifyUrl(): string {
    if (process.env["ALEPH_INTERNAL_URL"]) {
      return `${process.env["ALEPH_INTERNAL_URL"]}/api/auth/verify-access`;
    }
    const port = process.env["PORT"] || "3000";
    return `http://host.docker.internal:${port}/api/auth/verify-access`;
  }
}
