#!/usr/bin/env node
import { randomBytes } from "node:crypto";
import { mkdirSync, writeFileSync, existsSync } from "node:fs";
import { join, resolve } from "node:path";
import prompts from "prompts";

interface Answers {
  orgName: string;
  domain: string;
  port: number;
}

const DOCKER_COMPOSE_TEMPLATE = `# CHS Platform — docker-compose.yml
# Generated by create-chs CLI
#
# Start:   docker compose up -d
# Stop:    docker compose down
# Rebuild: docker compose build && docker compose up -d

services:
  platform:
    build:
      context: ./chs-platform-v2
      dockerfile: docker/Dockerfile
    ports:
      - "\${PORT:-3000}:3000"
    environment:
      - DATABASE_URL=\${DATABASE_URL}
      - JWT_SECRET=\${JWT_SECRET}
      - DOMAIN=\${DOMAIN}
      - ORG_NAME=\${ORG_NAME}
      - NODE_ENV=production
      - ANTHROPIC_API_KEY=\${ANTHROPIC_API_KEY:-}
      - AI_MODEL=\${AI_MODEL:-claude-sonnet-4-20250514}
      - AI_MAX_TOKENS=\${AI_MAX_TOKENS:-4096}
      - AI_RATE_LIMIT_MESSAGES_PER_HOUR=\${AI_RATE_LIMIT_MESSAGES_PER_HOUR:-50}
      - AI_RATE_LIMIT_TOKENS_PER_DAY=\${AI_RATE_LIMIT_TOKENS_PER_DAY:-100000}
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=chs
      - POSTGRES_USER=chs
      - POSTGRES_PASSWORD=\${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chs"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

volumes:
  pgdata:
`;

async function main(): Promise<void> {
  const targetDir = process.argv[2];
  const nonInteractive = process.argv.includes("--non-interactive");

  let answers: Answers;

  if (nonInteractive) {
    answers = {
      orgName: "CHS Demo",
      domain: "",
      port: 3000,
    };
  } else {
    if (!targetDir) {
      process.stderr.write("Usage: create-chs <directory> [--non-interactive]\n");
      process.exit(1);
    }

    const response = await prompts([
      {
        type: "text",
        name: "orgName",
        message: "Organization name:",
        initial: "My Company",
      },
      {
        type: "text",
        name: "domain",
        message: "Cookie domain (empty for localhost):",
        initial: "",
      },
      {
        type: "number",
        name: "port",
        message: "Port:",
        initial: 3000,
      },
    ]);

    answers = response as Answers;
  }

  const dir = resolve(targetDir || "/tmp/chs-test-cli");

  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true });
  }

  const jwtSecret = randomBytes(64).toString("hex");
  const pgPassword = randomBytes(32).toString("hex");
  const dbUrl = `postgresql://chs:${pgPassword}@db:5432/chs`;

  const envContent = [
    `# CHS Platform — Environment`,
    `# Generated by create-chs CLI`,
    ``,
    `# Organization`,
    `ORG_NAME=${answers.orgName}`,
    `DOMAIN=${answers.domain}`,
    `PORT=${answers.port}`,
    ``,
    `# Database`,
    `DATABASE_URL=${dbUrl}`,
    `POSTGRES_PASSWORD=${pgPassword}`,
    ``,
    `# Auth (auto-generated, keep secret)`,
    `JWT_SECRET=${jwtSecret}`,
    ``,
    `# AI Agent (optional)`,
    `ANTHROPIC_API_KEY=`,
    `AI_MODEL=claude-sonnet-4-20250514`,
    `AI_MAX_TOKENS=4096`,
    `AI_RATE_LIMIT_MESSAGES_PER_HOUR=50`,
    `AI_RATE_LIMIT_TOKENS_PER_DAY=100000`,
    ``,
    `# Node`,
    `NODE_ENV=production`,
    ``,
  ].join("\n");

  writeFileSync(join(dir, ".env"), envContent);
  writeFileSync(join(dir, "docker-compose.yml"), DOCKER_COMPOSE_TEMPLATE);

  const readmeContent = [
    `# ${answers.orgName} — CHS Platform`,
    ``,
    `## Quick Start`,
    ``,
    "```bash",
    `# 1. Clone chs-platform-v2 into this directory`,
    `git clone https://github.com/smellak/chs-platform-v2.git`,
    ``,
    `# 2. Start services`,
    `docker compose up -d`,
    ``,
    `# 3. Open in browser`,
    `# http://localhost:${answers.port}`,
    `# Login: admin / admin123`,
    "```",
    ``,
    `## Configuration`,
    ``,
    `Edit \`.env\` to change:`,
    `- \`ORG_NAME\` — Organization name shown in the UI`,
    `- \`DOMAIN\` — Cookie domain for cross-domain SSO`,
    `- \`ANTHROPIC_API_KEY\` — Enable AI agent (optional)`,
    ``,
    `## Update`,
    ``,
    "```bash",
    `cd chs-platform-v2 && git pull`,
    `cd .. && docker compose build && docker compose up -d`,
    "```",
    ``,
  ].join("\n");

  writeFileSync(join(dir, "README.md"), readmeContent);

  process.stdout.write(`\n  CHS Platform setup created at: ${dir}\n\n`);
  process.stdout.write(`  Next steps:\n`);
  process.stdout.write(`    cd ${dir}\n`);
  process.stdout.write(`    git clone https://github.com/smellak/chs-platform-v2.git\n`);
  process.stdout.write(`    docker compose up -d\n`);
  process.stdout.write(`\n`);
  process.stdout.write(`  Then open http://localhost:${answers.port}\n`);
  process.stdout.write(`  Login: admin / admin123\n\n`);
}

main().catch((err: unknown) => {
  const msg = err instanceof Error ? err.message : "Unknown error";
  process.stderr.write(`Error: ${msg}\n`);
  process.exit(1);
});
